// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseKey: typeof import('./src/components/UI/BaseKey.vue')['default']
    BaseThemeControl: typeof import('./src/components/UI/BaseThemeControl.vue')['default']
    MainCalculator: typeof import('./src/components/Page/MainCalculator.vue')['default']
    TheDisplayWindow: typeof import('./src/components/Layout/TheDisplayWindow.vue')['default']
    TheHeader: typeof import('./src/components/Layout/TheHeader.vue')['default']
    TheKeypad: typeof import('./src/components/Layout/TheKeypad.vue')['default']
  }
}
